# Generated by Django 5.0.3 on 2024-03-24 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.TextField(max_length=20, unique=True)),
                ("description", models.TextField(max_length=255)),
                ("image", models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Card",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.TextField(max_length=20, unique=True)),
                ("description", models.TextField(max_length=255)),
                ("image", models.TextField(max_length=100)),
                ("type", models.TextField(max_length=10)),
                ("symbol", models.TextField(max_length=10)),
                ("bandit_occurence", models.IntegerField(default=0)),
                ("cowboy_occurence", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Character",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.TextField(max_length=20, unique=True)),
                ("description", models.TextField(max_length=255)),
                ("image", models.TextField(max_length=30)),
                ("hit_points", models.IntegerField(default=3)),
                ("is_bandit", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.TextField(max_length=20, unique=True)),
                ("profile_pic", models.TextField(max_length=30)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PlayerAchievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "achievement_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="database.achievement",
                    ),
                ),
                (
                    "player_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="database.player",
                    ),
                ),
            ],
        ),
    ]
