# Generated by Django 5.0.3 on 2024-04-02 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="description",
            field=models.TextField(max_length=280),
        ),
    ]
