# Generated by Django 5.0.3 on 2024-04-02 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0003_alter_player_options_player_groups_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="player",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="player",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
