# Generated by Django 5.0.3 on 2024-04-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0004_player_is_active_player_is_staff_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="name",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
