# Generated by Django 5.0.3 on 2024-04-25 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0005_alter_player_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="wins",
            field=models.IntegerField(default=0),
        ),
    ]
