# Generated by Django 5.0.3 on 2024-04-25 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0006_player_wins"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="profile_pic",
        ),
    ]
